### ISSUE TITLE
?????

### ISSUE THREAD

**Issue by dongpu1813** [CommanderXanon/Xcoin#1]
pool@vultr:~/daemon/xcn$ ll
total 9840
drwxrwxr-x 2 pool pool     4096 Jun 19 23:53 ./
drwxrwxr-x 7 pool pool     4096 Jun 19 23:45 ../
-rwxrwxr-x 1 pool pool 10064704 Jun 19 23:53 xcoind*
pool@vultr:~/daemon/xcn$ sudo ./xcoind
./xcoind: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./xcoind)
./xcoind: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by ./xcoind)
./xcoind: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./xcoind)
pool@vultr:~/daemon/xcn$

**Comment by CommanderXanon** [comment]
Looks like you may be missing a dependency.
